"""anti-client: High-performance Python SDK and Agent for Google Cloud Code / Antigravity API.

Provides seamless OAuth 2.0 authentication, streaming chat completions,
native search grounding, image generation, token counting, atomic history management,
and Model Context Protocol (MCP) support.
"""

from .agent import Agent
from .client import (
    API_ENDPOINTS,
    DEFAULT_CLIENT_HEADERS,
    DEFAULT_PROJECT_ID,
    Client,
    ModelsResource,
    QuotaResource,
    authenticate,
    get_account,
    get_clean_display_name,
    get_default_headers,
    list_accounts,
    logout,
    parse_effort_from_suffix,
    remove_account,
    resolve_accounts_path,
    sanitize_params_for_google,
    save_account,
    set_active_account,
)
from .exceptions import (
    AgentAPIError,
    AgentMaxStepsError,
    AuthError,
    ModelNotFoundError,
    RateLimitError,
    ToolExecutionError,
)
from .mcp import (
    MCPAdapter,
    MCPSessionProtocol,
    MCPToolProtocol,
    load_mcp_tools,
)
from .types import (
    ChatResponse,
    Citation,
    CodeAssistInfo,
    CountTokensResult,
    FileAttachment,
    GenerateOptions,
    ImageGenerationResponse,
    Message,
    ModelInfo,
    ModelQuota,
    ModelsCatalog,
    QuotaBucket,
    QuotaGroup,
    QuotaInfo,
    QuotaSummary,
    SafetyRating,
    SearchResponse,
    SearchSource,
    StreamChunk,
    TierInfo,
    TokenDetail,
    Tool,
    ToolCall,
    UsageStats,
)

__version__ = "1.3.0"

__all__ = [
    "API_ENDPOINTS",
    "DEFAULT_CLIENT_HEADERS",
    "DEFAULT_PROJECT_ID",
    "Agent",
    "AgentAPIError",
    "AgentMaxStepsError",
    "AuthError",
    "ChatResponse",
    "Citation",
    "Client",
    "CodeAssistInfo",
    "CountTokensResult",
    "FileAttachment",
    "GenerateOptions",
    "ImageGenerationResponse",
    "MCPAdapter",
    "MCPSessionProtocol",
    "MCPToolProtocol",
    "Message",
    "ModelInfo",
    "ModelNotFoundError",
    "ModelQuota",
    "ModelsCatalog",
    "ModelsResource",
    "QuotaBucket",
    "QuotaGroup",
    "QuotaInfo",
    "QuotaResource",
    "QuotaSummary",
    "RateLimitError",
    "SafetyRating",
    "SearchResponse",
    "SearchSource",
    "StreamChunk",
    "TierInfo",
    "TokenDetail",
    "Tool",
    "ToolCall",
    "ToolExecutionError",
    "UsageStats",
    "__version__",
    "authenticate",
    "get_account",
    "get_clean_display_name",
    "get_default_headers",
    "list_accounts",
    "load_mcp_tools",
    "logout",
    "parse_effort_from_suffix",
    "remove_account",
    "resolve_accounts_path",
    "sanitize_params_for_google",
    "save_account",
    "set_active_account",
]
