"""Data types, schemas, request/response models, and results for anti-client."""

from __future__ import annotations

import base64
import mimetypes
import os
from collections.abc import Callable
from dataclasses import dataclass, field
from typing import Any, Literal


@dataclass
class GenerateOptions:
    """Configuration options for generation requests.

    Attributes:
        temperature (Optional[float]): Sampling temperature.
        max_output_tokens (Optional[int]): Maximum number of tokens to generate.
        top_p (Optional[float]): Top-p sampling probability threshold.
        top_k (Optional[int]): Top-k sampling candidates limit.
        stop_sequences (Optional[List[str]]): Stop sequences to halt generation.
        thinking_budget (Optional[int]): Maximum thinking budget in tokens.
        thinking_level (Optional[str]): Thinking effort level ('low', 'medium', 'high', etc.).
        safety_settings (Optional[List[Dict[str, Any]]]): Custom safety threshold settings.
        max_steps (int): Maximum tool execution steps for agents.
        tool_timeout (Optional[float]): Execution timeout for tools in seconds.
        on_max_steps (Optional[Literal["raise", "return_last"]]): Behavior when max_steps is reached.
    """

    temperature: float | None = 0.8
    max_output_tokens: int | None = None
    top_p: float | None = None
    top_k: int | None = None
    stop_sequences: list[str] | None = None
    thinking_budget: int | None = None
    thinking_level: str | None = None
    safety_settings: list[dict[str, Any]] | None = None
    max_steps: int = 5
    tool_timeout: float | None = None
    on_max_steps: Literal["raise", "return_last"] | None = None


@dataclass
class FileAttachment:
    """Represents a file attachment to be sent with a message or generated by the model.

    Attributes:
        mime_type (str): The MIME type of the file (e.g., 'image/png').
        data (str): The base64-encoded string of the file's content.
    """

    mime_type: str
    data: str

    @classmethod
    def from_file(cls, file_path: str, mime_type: str | None = None) -> FileAttachment:
        """Creates a FileAttachment by reading a local file.

        Args:
            file_path (str): Path to the local file.
            mime_type (Optional[str]): Explicit MIME type. If None, guessed from file extension.

        Returns:
            FileAttachment: Initialized instance with base64 encoded content.
        """
        if not mime_type:
            guessed_type, _ = mimetypes.guess_type(file_path)
            mime_type = guessed_type or "application/octet-stream"
        with open(file_path, "rb") as f:
            encoded = base64.b64encode(f.read()).decode("utf-8")
        return cls(mime_type=mime_type, data=encoded)

    @classmethod
    def from_bytes(cls, raw_bytes: bytes, mime_type: str = "image/png") -> FileAttachment:
        """Creates a FileAttachment directly from raw bytes.

        Args:
            raw_bytes (bytes): Raw binary data.
            mime_type (str): MIME type of the data (default: 'image/png').

        Returns:
            FileAttachment: Initialized instance with base64 encoded content.
        """
        encoded = base64.b64encode(raw_bytes).decode("utf-8")
        return cls(mime_type=mime_type, data=encoded)

    def to_bytes(self, validate: bool = True) -> bytes:
        """Decodes the base64 data into raw bytes.

        Args:
            validate (bool): If True, strictly validates that the string contains valid base64 data.

        Returns:
            bytes: The binary representation of the attachment.
        """
        return base64.b64decode(self.data, validate=validate)

    def save(self, file_path: str) -> None:
        """Saves the attachment directly to a file on disk.

        Args:
            file_path (str): Destination file path.
        """
        parent_dir = os.path.dirname(file_path)
        if parent_dir:
            os.makedirs(parent_dir, exist_ok=True)
        with open(file_path, "wb") as f:
            f.write(self.to_bytes())


@dataclass
class ToolCall:
    """Represents a tool call requested by the model.

    Attributes:
        id (str): A unique identifier for the tool call.
        name (str): The name of the tool/function to call.
        arguments (Dict[str, Any]): The arguments to pass to the tool.
        thought_signature (Optional[str]): An optional signature representing the model's reasoning process.
    """

    id: str
    name: str
    arguments: dict[str, Any]
    thought_signature: str | None = None


@dataclass
class Tool:
    """Represents an executable tool that the agent can use.

    Attributes:
        name (str): The name of the tool.
        description (str): A description of what the tool does.
        parameters (Dict[str, Any]): A JSON schema describing the tool's parameters.
        func (Optional[Callable]): The actual Python function (sync or async) to execute.
    """

    name: str
    description: str
    parameters: dict[str, Any]
    func: Callable | None = None
    timeout: float | None = None

    @classmethod
    def from_mcp(cls, mcp_tool: Any, session: Any) -> Tool:
        """Creates a Tool instance from an MCP (Model Context Protocol) tool.

        Args:
            mcp_tool (Any): An MCP Tool object.
            session (Any): An active MCP ClientSession used to execute the tool.

        Returns:
            Tool: A Tool instance configured to invoke the MCP tool via the session.
        """
        name = getattr(mcp_tool, "name", str(mcp_tool))
        description = getattr(mcp_tool, "description", "") or ""
        parameters = (
            getattr(mcp_tool, "inputSchema", None)
            or getattr(mcp_tool, "parameters", None)
            or {"type": "object", "properties": {}}
        )

        async def mcp_func(**kwargs) -> Any:
            result = await session.call_tool(name, arguments=kwargs)
            if hasattr(result, "content"):
                contents = []
                for item in result.content:
                    if hasattr(item, "text"):
                        contents.append(item.text)
                    else:
                        contents.append(str(item))
                return "\n".join(contents)
            return str(result)

        return cls(
            name=name,
            description=description,
            parameters=parameters,
            func=mcp_func,
        )


@dataclass
class Message:
    """Represents a message in the conversation history.

    Attributes:
        role (str): The role of the message sender ('user', 'assistant', 'system', 'tool').
        content (Optional[str]): The text content of the message.
        name (Optional[str]): Name of the tool or sender.
        thought (Optional[str]): Chain-of-thought reasoning text.
        thought_signature (Optional[str]): Reasoning signature from the model.
        tool_calls (Optional[List[ToolCall]]): Tool calls initiated in this message.
        tool_call_id (Optional[str]): The ID of the tool call this message is responding to.
        attachments (Optional[List[FileAttachment]]): File attachments included with the message.
    """

    role: str
    content: str | None = None
    name: str | None = None
    thought: str | None = None
    thought_signature: str | None = None
    tool_calls: list[ToolCall] | None = None
    tool_call_id: str | None = None
    attachments: list[FileAttachment] | None = None


@dataclass
class TokenDetail:
    """Detailed breakdown of tokens by modality."""

    modality: str
    token_count: int


@dataclass
class UsageStats:
    """Holds token usage statistics for a generation request.

    Attributes:
        prompt_tokens (int): The number of tokens in the prompt.
        completion_tokens (int): The number of tokens generated in the response.
        total_tokens (int): The total number of tokens used.
        cached_tokens (int): The number of cached tokens in the prompt.
        thoughts_tokens (int): The number of reasoning/thinking tokens.
        candidates_token_details (Optional[List[TokenDetail]]): Breakdown of response tokens.
        prompt_token_details (Optional[List[TokenDetail]]): Breakdown of prompt tokens.
    """

    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    cached_tokens: int = 0
    thoughts_tokens: int = 0
    candidates_token_details: list[TokenDetail] | None = None
    prompt_token_details: list[TokenDetail] | None = None


@dataclass
class Citation:
    """Represents a citation or attribution source for generated text."""

    start_index: int
    end_index: int
    uri: str
    title: str | None = None
    license: str | None = None


@dataclass
class SafetyRating:
    """Safety evaluation rating returned by Google API."""

    category: str
    probability: str
    blocked: bool = False


@dataclass
class ChatResponse:
    """Represents the final response from a chat generation request.

    Attributes:
        text (Optional[str]): The generated text content.
        thought (Optional[str]): Chain-of-thought reasoning text.
        thought_signature (Optional[str]): Reasoning signature.
        usage (Optional[UsageStats]): Token usage statistics.
        finish_reason (str): Reason generation completed ('STOP', 'MAX_TOKENS', 'SAFETY', etc.).
        tool_calls (Optional[List[ToolCall]]): Any tool calls requested by the model.
        safety_ratings (Optional[List[SafetyRating]]): Safety assessment ratings.
        citations (Optional[List[Citation]]): Attributions and citations.
        model_version (Optional[str]): The backend version identifier of the model.
        response_id (Optional[str]): Unique response trace identifier.
    """

    text: str | None = None
    thought: str | None = None
    thought_signature: str | None = None
    usage: UsageStats | None = None
    finish_reason: str = "stop"
    tool_calls: list[ToolCall] | None = None
    safety_ratings: list[SafetyRating] | None = None
    citations: list[Citation] | None = None
    model_version: str | None = None
    response_id: str | None = None


@dataclass
class StreamChunk:
    """Represents a chunk emitted during streaming generation.

    Attributes:
        text (Optional[str]): The generated text content chunk.
        thought (Optional[str]): The generated thinking/reasoning chunk.
        thought_signature (Optional[str]): Reasoning signature for this chunk or tool call.
        tool_calls (Optional[List[ToolCall]]): Any tool calls in this chunk.
        usage (Optional[UsageStats]): Token usage statistics if emitted.
        finish_reason (Optional[str]): Finish reason if emitted in chunk.
        safety_ratings (Optional[List[SafetyRating]]): Safety ratings if present.
        citations (Optional[List[Citation]]): Citations if present.
        model_version (Optional[str]): Model version if present.
        response_id (Optional[str]): Response ID if present.
    """

    text: str | None = None
    thought: str | None = None
    thought_signature: str | None = None
    tool_calls: list[ToolCall] | None = None
    usage: UsageStats | None = None
    finish_reason: str | None = None
    safety_ratings: list[SafetyRating] | None = None
    citations: list[Citation] | None = None
    model_version: str | None = None
    response_id: str | None = None

    @property
    def is_thought(self) -> bool:
        return self.thought is not None

    @property
    def is_text(self) -> bool:
        return self.text is not None

    @property
    def is_tool_call(self) -> bool:
        return self.tool_calls is not None

    def __str__(self) -> str:
        if self.text is not None:
            return self.text
        if self.thought is not None:
            return self.thought
        return ""


@dataclass
class SearchSource:
    """A web source returned by Google Search Grounding."""

    title: str
    uri: str


@dataclass
class SearchResponse:
    """Response from a web search grounding request.

    Attributes:
        text: Synthesized response text using search results.
        sources: List of web citations with title and URI.
        grounding_metadata: Full raw grounding metadata from API.
        usage: Token usage stats.
        model_version: Model version identifier.
    """

    text: str
    sources: list[SearchSource] = field(default_factory=list)
    grounding_metadata: dict[str, Any] | None = None
    usage: UsageStats | None = None
    model_version: str | None = None


@dataclass
class ImageGenerationResponse:
    """Response from an image generation request.

    Attributes:
        images: List of generated images as FileAttachment objects.
        usage: Token usage stats.
        model_version: Model version identifier.
    """

    images: list[FileAttachment] = field(default_factory=list)
    usage: UsageStats | None = None
    model_version: str | None = None

    @property
    def image(self) -> FileAttachment | None:
        """Returns the primary generated image if available."""
        return self.images[0] if self.images else None


@dataclass
class ModelQuota:
    """Contains quota information for a specific model.

    Attributes:
        remaining_fraction (float): The remaining fraction of the quota (0.0 to 1.0).
        reset_time (Optional[str]): The timestamp when the quota resets.
    """

    remaining_fraction: float
    reset_time: str | None = None


# Alias for backward compatibility
QuotaInfo = ModelQuota


@dataclass
class ModelInfo:
    """Contains metadata and configuration for an available model.

    Attributes:
        id (str): The identifier of the model (e.g. 'gemini-3.5-flash-low').
        display_name (str): The raw display name returned by the API.
        clean_display_name (str): Human-readable name stripped of effort/thinking suffixes.
        internal_model_id (str): The internal identifier (e.g. 'MODEL_PLACEHOLDER_M20').
        model_provider (str): The provider of the model ('MODEL_PROVIDER_GOOGLE', etc.).
        api_provider (str): The API provider backend.
        max_tokens (int): The maximum number of total context tokens supported.
        max_output_tokens (Optional[int]): The maximum number of output tokens.
        supports_images (bool): Whether the model supports image inputs.
        supports_video (bool): Whether the model supports video inputs.
        supports_thinking (bool): Whether the model supports reasoning/thinking.
        supported_efforts (Optional[List[str]]): List of supported effort levels, None if unknown/unvalidated, [] if thinking not supported.
        thinking_level (Optional[str]): Effort level parsed from suffix ('low', 'medium', 'high', 'extra-low').
        thinking_budget (Optional[int]): Maximum reasoning token budget.
        min_thinking_budget (Optional[int]): Minimum reasoning token budget.
        recommended (bool): Whether this model is marked recommended.
        is_internal (bool): Whether the model is an internal-only model.
        tag_title (Optional[str]): Optional tag title (e.g. 'Fast').
        tag_description (Optional[str]): Optional tag description.
        quota_info (Optional[ModelQuota]): Model-specific quota info if available.
        supported_mime_types (Optional[Dict[str, bool]]): Supported input MIME types.
        model_experiments (Optional[Dict[str, Any]]): Model experiment flags.
    """

    id: str
    display_name: str
    clean_display_name: str
    internal_model_id: str
    model_provider: str
    api_provider: str
    max_tokens: int
    max_output_tokens: int | None = None
    supports_images: bool = False
    supports_video: bool = False
    supports_thinking: bool = False
    supported_efforts: list[str] | None = None
    thinking_level: str | None = None
    thinking_budget: int | None = None
    min_thinking_budget: int | None = None
    recommended: bool = False
    is_internal: bool = False
    tag_title: str | None = None
    tag_description: str | None = None
    quota_info: ModelQuota | None = None
    supported_mime_types: dict[str, bool] | None = None
    model_experiments: dict[str, Any] | None = None


@dataclass
class ModelsCatalog:
    """Catalog of available models and specialized category listings.

    Attributes:
        models (List[ModelInfo]): All discovered model definitions.
        default_agent_model_id (str): Recommended default agent model ID.
        agent_model_sorts (List[str]): Preferred sort order of agent model IDs.
        deprecated_model_ids (List[str]): List of deprecated model IDs.
        deprecated_model_map (Dict[str, str]): Mapping of deprecated model IDs to recommended alternatives.
        web_search_model_ids (List[str]): Models supporting web search grounding.
        image_generation_model_ids (List[str]): Models supporting image generation.
        command_model_ids (List[str]): Models optimized for command execution.
        mquery_model_ids (List[str]): Models for multi-query execution.
        commit_message_model_ids (List[str]): Models for commit message generation.
        audio_transcription_model_ids (List[str]): Models for audio transcription.
        tab_model_ids (List[str]): Models for code completion/tab suggestions.
        tiered_model_ids (Optional[Dict[str, List[str]]]): Groupings of tiered model IDs.
    """

    models: list[ModelInfo]
    default_agent_model_id: str = "gemini-3.1-pro-low"
    agent_model_sorts: list[str] = field(default_factory=list)
    deprecated_model_ids: list[str] = field(default_factory=list)
    deprecated_model_map: dict[str, str] = field(default_factory=dict)
    web_search_model_ids: list[str] = field(default_factory=list)
    image_generation_model_ids: list[str] = field(default_factory=list)
    command_model_ids: list[str] = field(default_factory=list)
    mquery_model_ids: list[str] = field(default_factory=list)
    commit_message_model_ids: list[str] = field(default_factory=list)
    audio_transcription_model_ids: list[str] = field(default_factory=list)
    tab_model_ids: list[str] = field(default_factory=list)
    tiered_model_ids: dict[str, list[str]] | None = None

    def get_model(self, model_id: str) -> ModelInfo | None:
        """Finds a model by its ID or internal model ID."""
        for m in self.models:
            if m.id == model_id or m.internal_model_id == model_id:
                return m
        return None


@dataclass
class QuotaBucket:
    """Individual quota bucket for a specific window."""

    bucket_id: str
    display_name: str
    window: str  # "weekly" | "5h"
    reset_time: str
    description: str
    remaining_fraction: float


@dataclass
class QuotaGroup:
    """Group of quota buckets sharing limits (e.g. Gemini Models, Claude and GPT)."""

    display_name: str
    description: str
    buckets: list[QuotaBucket] = field(default_factory=list)

    @property
    def weekly(self) -> QuotaBucket | None:
        """Returns the weekly limit quota bucket if present."""
        return next(
            (b for b in self.buckets if b.window == "weekly" or "weekly" in b.bucket_id.lower()),
            None,
        )

    @property
    def five_hour(self) -> QuotaBucket | None:
        """Returns the 5-hour limit quota bucket if present."""
        return next(
            (b for b in self.buckets if b.window == "5h" or "5h" in b.bucket_id.lower()),
            None,
        )


@dataclass
class QuotaSummary:
    """Summary of user quota status across model families."""

    groups: list[QuotaGroup] = field(default_factory=list)
    description: str = ""

    @property
    def gemini(self) -> QuotaGroup | None:
        """Returns quota group for Gemini models."""
        return next(
            (g for g in self.groups if "gemini" in g.display_name.lower()),
            None,
        )

    @property
    def claude(self) -> QuotaGroup | None:
        """Returns quota group for Claude and 3P models."""
        return next(
            (
                g
                for g in self.groups
                if any(
                    k in g.display_name.lower()
                    for k in ("claude", "gpt", "3p", "anthropic", "openai")
                )
            ),
            None,
        )


@dataclass
class TierInfo:
    """Subscription tier details from loadCodeAssist."""

    id: str
    name: str
    description: str
    upgrade_subscription_uri: str | None = None
    upgrade_subscription_text: str | None = None
    is_default: bool = False
    user_defined_companion_project: bool = False
    uses_gcp_tos: bool = False


@dataclass
class CodeAssistInfo:
    """Full account and subscription status from loadCodeAssist."""

    current_tier: TierInfo | None
    allowed_tiers: list[TierInfo]
    companion_project_id: str
    gcp_managed: bool
    paid_tier: dict[str, Any] | None = None
    upgrade_subscription_uri: str | None = None


@dataclass
class CountTokensResult:
    """Result from the countTokens endpoint."""

    total_tokens: int

    def __int__(self) -> int:
        return self.total_tokens

    def __index__(self) -> int:
        return self.total_tokens

    def __repr__(self) -> str:
        return f"CountTokensResult(total_tokens={self.total_tokens})"

    def __eq__(self, other: object) -> bool:
        if isinstance(other, int):
            return self.total_tokens == other
        if isinstance(other, CountTokensResult):
            return self.total_tokens == other.total_tokens
        return False

    def __lt__(self, other: Any) -> bool:
        if isinstance(other, (int, CountTokensResult)):
            return self.total_tokens < int(other)
        return NotImplemented

    def __le__(self, other: Any) -> bool:
        if isinstance(other, (int, CountTokensResult)):
            return self.total_tokens <= int(other)
        return NotImplemented

    def __gt__(self, other: Any) -> bool:
        if isinstance(other, (int, CountTokensResult)):
            return self.total_tokens > int(other)
        return NotImplemented

    def __ge__(self, other: Any) -> bool:
        if isinstance(other, (int, CountTokensResult)):
            return self.total_tokens >= int(other)
        return NotImplemented

    def __add__(self, other: Any) -> int:
        if isinstance(other, (int, CountTokensResult)):
            return self.total_tokens + int(other)
        return NotImplemented

    def __radd__(self, other: Any) -> int:
        if isinstance(other, (int, CountTokensResult)):
            return int(other) + self.total_tokens
        return NotImplemented

    def __sub__(self, other: Any) -> int:
        if isinstance(other, (int, CountTokensResult)):
            return self.total_tokens - int(other)
        return NotImplemented
